server:
  port: 0
  error:
    whitelabel:
      enabled: false

debug: true

logging.file: /var/log/${spring.application.name}.log 
logging.pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

logging:
  level:
    org.springframework.security: info

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://jps-01368:5432/events
    username: events
    password: password
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    database: postgresql
    hibernate: 
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect
      
test_consul.my_name: kiton
 

