server:
  port: 8182
  error:
    whitelabel:
      enabled: true
    

debug: true

logging.file: /var/log/${spring.application.name}.log 
logging.pattern.file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"

logging:
  level:
    org.springframework.security: info

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/otong_db
    username: otong
    password: password
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    database: postgresql
    hibernate: 
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL95Dialect

  session:
    timeout: 
      seconds: 120
  boot:
    admin:
      client:
        instance:
          metadata:
            user.name: admin
            user.password: password            
        username: admin
        password: password
        auto-deregistration: true
      
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: never

spring.boot.admin.client.url: http://localhost:7070
